# VECTORS

Vectors are ordered arrays of numbers. In notation, vectors are denoted with lower case bold letters such as  𝐱
 . The elements of a vector are all the same type. A vector does not, for example, contain both characters and numbers. The number of elements in the array is often referred to as the dimension though mathematicians may prefer rank. In math settings, indexes typically run from 1 to n. In computer science and these labs, indexing will typically run from 0 to n-1.

 In Python, the NumPy library provides multiple ways to create vectors such as using numpy.array, numpy.zeros, numpy.arange, numpy.ones, numpy.linspace and many more

In [2]:
import numpy as np

In [7]:
v=np.zeros(4)           #creat a zero vector of dimension four
v

array([0., 0., 0., 0.])

In [10]:
v=np.linspace(1,2,5)    #generates a vector with evenly spaced numbers between a start and stop value.
v

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
v=np.arange(2,5,0.5)    #this function generates a sequence of numbers with a specified range and step size.
v

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
v=np.array([1,2,3,4,5])    #this will create a vector by directly defining its elements
v

array([1, 2, 3, 4, 5])

We can get the shape of the vector using shape attribute.

In [20]:
v.shape

(5,)

# Indexing and slicing

Elements of vectors can be accessed via indexing and slicing. 
Indexing means referring to an element of an array by its position within the array.
Slicing means getting a subset of elements from an array based on their indices. We can creat a slice of vector using a set of three values (start:stop:step).

In [45]:
v=np.array([2,4,6,8,10,12,14])
v[-1]        #this will access the last element of the vector. 

14

In [46]:
v[1:5]       #this will access the elements from second position to 4th position

array([ 4,  6,  8, 10])

In [50]:
v[0:7:2]     #this will access the elements from first position to 6th position separated by two.

array([ 2,  6, 10, 14])

In [52]:
v[3:]     #this will access all the elements above fourth position inclusive

array([ 8, 10, 12, 14])

If we want to access the elements from the last position, we can use negative indexes.

# Single vector operations

There are a number of useful operations that involve operations on a single vector.

In [53]:
v

array([ 2,  4,  6,  8, 10, 12, 14])

In [55]:
np.sum(v)    #this will provide the sum of all the elements of the vector

56

Likewise, we can use other methods such as np.mean, np.max, np.min and many more

# Vector vector element-wise operations

We can add, subtract, scalar multiplication, dot product and many more

In [83]:
a = np.array([1, 2, 3, 4])
b = 5 * a                    #this is scalar multiplication

In [84]:
c=a+b                           #this is addition of two vectors. Likewise, we can subtract two vectos
c

array([ 6, 12, 18, 24])

We can find dot product using the method np.dot. We can also find the manually using loops.

In [85]:
c=np.dot(a,b)                    
c 

150

In [93]:
def dot_prod(a,b):
    d=0
    for i, j in zip(a, b):
        k=i*j
        d=d+k
    return d 
dot_prod(a,b)

150

# MATRICES

Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1.

We can create matrices in the same way as vectors, manually and using builtin functions

In [97]:
x=np.zeros((2,2))
x

array([[0., 0.],
       [0., 0.]])

In [98]:
x=np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

In [100]:
x=np.random.random_sample((3, 2))
x

array([[0.75100977, 0.91156661],
       [0.06780164, 0.28683356],
       [0.41179412, 0.42920189]])

In [108]:
x=np.array([[1,2,3,4],
            [2,4,6,8], 
           [1,3,5,7]])
x, x.shape

(array([[1, 2, 3, 4],
        [2, 4, 6, 8],
        [1, 3, 5, 7]]),
 (3, 4))

We can also reshape one dimensional vector into higher dimensional vector using reshape method.

In [113]:
v=np.arange(10)
y=v.reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Indexing and slicing

Matrices use two indexes to access an element, row or column. The two indexes describe [row, column]. Access can either return an element or a row/column.

In [109]:
x

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [1, 3, 5, 7]])

In [115]:
x[0], x[1]          #this access the first and second row respectively

(array([1, 2, 3, 4]), array([2, 4, 6, 8]))

In [117]:
x[-1]              #this access the last row of the matrix

array([1, 3, 5, 7])

In [119]:
x[1,1]          #this access the element of second row and second column

4

In [125]:
x[:,0], x[:,-1]           #this access the first column and last column of the matrix

(array([1, 2, 1]), array([4, 8, 7]))

We can slice or access an element a matrix using a set of three values (start:stop:step).  

In [130]:
x[:, 0:3:2]       #this access all the rows and columns from first to third column with step two.

array([[1, 3],
       [2, 6],
       [1, 5]])

In [132]:
x[1:3,2:4]        #thiss access the elements in rows, second and third row and columns, third and fourth.  

array([[6, 8],
       [5, 7]])

In [134]:
x[:,:]         #this gives all the elements, original matrix.

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [1, 3, 5, 7]])